#!/usr/bin/env bash
# This script installs Nginx on a new Ubuntu machine and configures it to meet certain requirements.

# Update package lists and install Nginx with the "-y" flag to automatically answer "yes" to prompts
apt-get update
apt-get install -y nginx

sed -i 's/^\(listen\s*80;\)/\1 default_server;/' /etc/nginx/sites-available/default

/etc/init.d/nginx restart

echo "Hello World!" > /var/www/html/index.html
