#!/usr/bin/env bash
# This script displays lines containing the word "bash" to get the PID of the Bash process.

# shellcheck disable=SC2009
# Use ps command to list processes and grep for lines containing "bash"
ps auxf | grep bash
