#!/usr/bin/env bash
# This script displays information about each user in the /etc/passwd file using a while loop with IFS.

# Read the file /etc/passwd line by line
while IFS=":" read -r username _ uid gid info home shell; do
    # Extract the group name from /etc/group
    group=$(grep -E "^.*:x:$gid:" /etc/group | cut -d: -f1)
    # Extract the password from /etc/shadow
    password=$(grep -E "^$username:" /etc/shadow | cut -d: -f2)
    # Display the information
    echo "The user $username is part of the $group gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
