#!/usr/bin/env bash
# script that displays Best School 10 times, but for the 9th iteration, # displays Best School and then Hi on a new line.

#Initialise the counter 
counter=0

#while coungter is less than 10 keep iterating

while [ $counter -le 10 ];do
	# for the 9th iteration, displays Best School and then Hi
	if [ $counter == 9 ] ; then
		echo "Best School"
		echo "hi"
	else
		echo "Best School"
	fi
	((counter++))
done
