#!/usr/bin/env bash

# Write a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

# Initialise the counter 
counter=1

# while coungter is less than 10 keep iterating
while [ $counter -le 10 ];do
	# displays bad luck for the 4th loop iteration
	if [[ $counter -le 4 ]]; then
		echo "bad luck"
	# displays good luck for the 8th loop iteration
	elif [[ $counter -gt 4 ]] && [[ $counter -le 8 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
