#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8

# Update /etc/hosts file to map localhost to 127.0.0.2
sudo sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' /etc/hosts

# Update /etc/resolv.conf file to use 8.8.8.8 as the DNS server for facebook.com
echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
