#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to get information about network interfaces and filter IPv4 addresses
ip -4 addr show | grep -oP 'inet \K[\d.]+'
